import Head from 'next/head'
import { useRouter } from 'next/router'
import { useState, useEffect } from 'react'

async function Login(code: string): Promise<void> {
  const res = await fetch(
    `/github/login/oauth/access_token?client_id=24260c7de28ce45f53b5&client_secret=${process.env.CLIENT_SECRET}&code=${code}`,
    {
      method: 'POST',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
      },
    })
  const data = await res.json()
  window.sessionStorage.setItem('token', data.access_token)
}

export default function Home() {
  const router = useRouter()
  const { code } = router.query

  const [isLogin, setIsLogin] = useState(false)

  useEffect(() => {
    const token = window.sessionStorage.getItem('token')
    setIsLogin(token !== null)
  }, [])

  useEffect(() => {
    if (isLogin) {
      router.push('/task')
    } else if (code) {
      Login(code as string)
      .then(() => {
        setIsLogin(true)
        router.push('/task')
      })
    }
  }, [isLogin, code])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script>
        {/**
                                                      __----~~~~~~~~~~~------___
                                    .  .   ~~//====......          __--~ ~~
                    -.            \_|//     |||\\  ~~~~~~::::... /~
                 ___-==_       _-~o~  \/    |||  \\            _/~~-
         __---~~~.==~||\=_    -_--~/_-~|-   |\\   \\        _/~
     _-~~     .=~    |  \\-_    '-~7  /-   /  ||    \      /
   .~       .~       |   \\ -_    /  /-   /   ||      \   /
  /  ____  /         |     \\ ~-_/  /|- _/   .||       \ /
  |~~    ~~|--~~~~--_ \     ~==-/   | \~--===~~        .\
           '         ~-|      /|    |-~\~~       __--~~
                       |-~~-_/ |    |   ~\_   _-~            /\
                            /  \     \__   \/~                \__
                        _--~ _/ | .-~~____--~-/                  ~~==.
                       ((->/~   '.|||' -_|    ~~-/ ,              . _||
                                  -_     ~\      ~~---l__i__i__i--~~_/
                                  _-~-__   ~)  \--______________--~~
                                //.-~~~-~_--~- |-------~~~~~~~~
                                       //.-~~~--\
                                神獸保佑，程式碼沒Bug! 
        */}
        </script>
      </Head>
      <main>
        <a href="https://github.com/login/oauth/authorize?client_id=24260c7de28ce45f53b5&scope=user,repo">Login</a>
      </main>
    </>
  )
}
